import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import bg from "../public/bg/bg.png";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rabbit Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-white`}
      >
        <div className="fixed h-screen w-screen border-none -z-10 ">
          <img
            src={bg.src}
            alt="not found"
            className="w-full h-full object-cover"
          />
        </div>
        <div className="h-full w-full text-white">{children}</div>
      </body>
    </html>
  );
}
